INSERT INTO `clinic` (`id`, `google_place_id`, `group_id`, `is_group`, `logo`, `name`)
VALUES
(1, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', NULL, 1, 'https://www.garofalohealthcare.com/images/logo.png', 'Garofalo Health Care'),
(2, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'BALTIMORE VA MEDICAL CENTER'),
(3, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'RANSOM MEMORIAL HOSPITAL'),
(4, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'J. D. MCCARTY CENTER FOR CHILDREN WITH DEVELOPMENTAL'),
(5, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'KNOX COMMUNITY HOSPITAL'),
(6, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'BON SECOURS HOSPITAL'),
(7, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'ROBINSON MEMORIAL HOSPITAL'),
(8, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'ANMED HEALTH NORTH WOMEN\'S AND CHILDREN\'S HOSPITAL'),
(9, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'BIENVILLE MEDICAL CENTER'),
(10, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 1, 'https://www.garofalohealthcare.com/images/logo.png', 'OAK HILL HOSPITAL'),
(11, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'TAMPA COMMUNITY HOSPITAL'),
(12, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'WHITTIER REHABILITATION HOSPITAL'),
(13, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'OUR LADY OF PEACE'),
(14, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 1, 'https://www.garofalohealthcare.com/images/logo.png', 'DANIELS MEMORIAL HOSPITAL'),
(15, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'EDWARD PLAINFIELD'),
(16, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'TAMPA COMMUNITY HOSPITAL'),
(17, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'AURELIA OSBORN FOX MEMORIAL HOSPITAL'),
(18, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'UNIVERSITY HOSPITALS REHABILITATION HOSPITAL'),
(19, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'SURGICAL SPECIALTY CENTER AT COORDINATED HEALTH'),
(20, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'SPOKANE VA MEDICAL CENTER'),
(21, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 1, 1, 'https://www.garofalohealthcare.com/images/logo.png', 'QUITMAN COUNTY HOSPITAL'),
(22, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 10, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'OUR LADY OF LOURDES MEMORIAL HOSPITAL'),
(23, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 10, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'LADD MEMORIAL HOSPITAL'),
(24, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 10, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'FULTON MEDICAL CENTER'),
(25, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 10, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'ADVENTIST BOLINGBROOK HOSPITAL'),
(26, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 14, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'RANKEN JORDAN A PEDIATRIC REHABILITATION CENTER'),
(27, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 14, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'TOMAH MEM HSPTL'),
(28, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 14, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'MUSCOGEE (CREEK) NATION MEDICAL CENTER'),
(29, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 14, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'MARLBORO PARK HOSPITAL'),
(30, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 14, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'DAMERON HOSPITAL'),
(31, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 14, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'WATAUGA MEDICAL CENTER, INC.'),
(32, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 14, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'ASHLEY COUNTY MEDICAL CENTER'),
(33, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 14, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'KOOTENAI MEDICAL CENTER'),
(34, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 21, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'OJAI MANOR CONVALESCENT HOSPITAL'),
(35, 'ChIJvWb4_u9gLxMRkt2G2JoksHY', 21, 0, 'https://www.garofalohealthcare.com/images/logo.png', 'HOSP PEDIATRICO UNIVERSITARIO DR ANTONIO ORTIZ');
